### ISSUE TITLE
关于pretrained.yml文件的问题

### ISSUE THREAD

**Issue by porok1ng** [idejie/3DSyn#1]
作者您好，我是一名本科生，正在尝试复现您的论文，目前遇到了一些问题和疑问，希望能得到您的帮助。
1、我尝试进行预训练时出现报错，显示pretrained.yml文件中缺少refer_dataset项。请问这个配置项应该如何设置参数？
2、pretrained.yml文件中给出的预训练模型权重文件路径并不存在，请问您是否能提供预训练模型权重文件？
3、您项目中用于下载检查点的链接已失效，请问您是否能提供这些微调后的模型权重文件？
4、请问用于预训练的SynVL3D数据集存放在哪里，以及您是如何加载它的？
谢谢！

**Comment by idejie** [comment]
你好，我已经修改了yml文件
2和3的链接已经更新
4数据集有两种方式
（1）下载数据较大，推荐https://github.com/YandanYang/ai2thor.git内的方法进行导出
（2）使用【阿里云盘快传】 https://www.alipan.com/t/L6cn8kgR1FwHXFPNZhuJ

**Comment by whu125** [comment]
hi，请问你复现成功了吗

**Comment by porok1ng** [comment]
你好，我还没复现成功

**Comment by whu125** [comment]
hh我已经准备放弃了，这篇的预训练代码应该是自己加的，代码确实跑不通

**Comment by porok1ng** [comment]
确实，感觉错误的地方比较多
