### ISSUE TITLE
ScanQA权重文件错误

### ISSUE THREAD

**Issue by whu125** [idejie/3DSyn#3]
您好，感谢您的工作，最近在尝试复现您的项目，目前发现了两个问题
1、更新后的readme中ScanQA对应的link点进去是sr3d.pth
2、readme存在一个小小的笔误。运行文件的目录是configs,而非config

另外我在加载预训练时出现了报错：

  File "/xx/3DSyn/pipeline/registry.py", line 101, in get_language_model
    return cls.mapping["language_model"][name]
KeyError: 'vocabulary'
不知道您是否知道应该怎么处理，这个问题我先自己排查一下。
期待您的回复！

**Comment by whu125** [comment]
针对下面的问题。我读取生成的scanrefer_vocab.pth
然而我发现vocab并没有'token_to_id'
output_label.append(vocab.token_to_id('[EOS]'))

**Comment by whu125** [comment]
我修改了一下代码。这部分暂时没有问题了。然而出现了新的问题：
pipeline/pipeline_mixin.py
390行get_pretrain_loss函数中
total_loss, caption_cls_loss, obj_cls_raw_loss, obj_cls_pre_loss, obj_cls_post_loss = self.pretrain_loss(

但传入pretrain_loss中没有'replace'值，导致无法计算场景匹配的match_loss
请问这个值应该怎么产生呢

**Comment by idejie** [comment]
这里应该对应的是mask token
这个地方是由3D-Vista实现的，您可以参考原repo： https://github.com/3d-vista/3D-VisTA

**Comment by whu125** [comment]
感谢回答。能否更新一下权重文件：)
